#ifndef HASH_TABLE_ERROR_TYPES_H_
#define HASH_TABLE_ERROR_TYPES_H_

typedef enum {
    HASH_TABLE_ERROR_NO,
    HASH_TABLE_ALLOCATION_FAILED,
    HASH_TABLE_ERROR_OPENING_FILE,
    HASH_TABLE_NULL_POINTER,
    HASH_TABLE_LIST_ERROR,
    HASH_TABLE_HISTOGRAM_ERROR,
    HASH_TABLE_CAPACITY_IS_ZERO,
    HASH_TABLE_ELEMENT_NOT_FOUND
} HashTableErrorType;

#endif // HASH_TABLE_ERROR_TYPES_H_
