#ifndef HASH_TABLE_ERROR_TYPES_H_
#define HASH_TABLE_ERROR_TYPES_H_

typedef enum {
    HASH_TABLE_ERROR_NO,
    HASH_TABLE_ALLOCATION_FAILED,
    HASH_TABLE_ERROR_OPENING_FILE,
    HASH_TABLE_NULL_POINTER,
    HASH_TABLE_ERROR_WITH_LIST
} HashTableErrorType;

#endif // HASH_TABLE_ERROR_TYPES_H_
